version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      github-actions-patch:
        applies-to: version-updates
        update-types:
          - "patch"
      rollkit-actions:
        patterns:
          - "rollkit/*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      go-patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
      rollkit-go-deps:
        patterns:
          - "github.com/rollkit/*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      docker-patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
