version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    groups:
      actions-patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "github.com/rollkit/*"
        update-types: []
    groups:
      rollkit-dependencies:
        patterns:
          - "github.com/rollkit/*"
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
    ignore:
      - dependency-name: "github.com/rollkit/*"
    groups:
      go-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/rollkit/*"
      go-patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
        exclude-patterns:
          - "github.com/rollkit/*"
